name: Build Examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@latest

      - name: Set up Arduino CLI
        uses: arduino/setup-cli@latest

      - name: Compile All Example Sketches
        uses: arduino/compile-sketches@latest
        with:
          board: arduino:avr:mega
          sketch: ./examples
          
