name: Build Examples

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: arduino:avr:nano
            platforms: |
              - name: arduino:avr
            artifact-name-suffix: arduino-avr-nano
          - fqbn: arduino:avr:mega
            platforms: |
              - name: arduino:avr
            artifact-name-suffix: arduino-avr-mega
          - fqbn: arduino:avr:leonardo
            platforms: |
              - name: arduino:avr
            artifact-name-suffix: arduino-avr-leonardo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Compile examples
        uses: arduino/compile-sketches@v1.1.2
        with:
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          libraries: |
            # Install the library from the local path.
            - source-path: ./
            # Additional library dependencies can be listed here.
            # See: https://github.com/arduino/compile-sketches#libraries
          sketch-paths: |
            - examples
          enable-deltas-report: true
